
spa.available=true
spa.version=10.0.5.0.v202512120852
spa.plugin.loc=C:/Users/omars/Iris/workspace/bundles/com.kony.spa
rentokilUi_spatargetplatforms=desktopweb
desktopweb.available=true
desktopweb.version=10.0.5.0.v202512120852
desktopweb.plugin.loc=C:/Users/omars/Iris/workspace/bundles/com.kony.desktopweb
rentokilUi_tctargetplatforms=
tc.plugin.loc=
tc.available=false
webcommons.plugin.loc=C:/Users/omars/Iris/workspace/bundles/com.kony.webcommons
webcommons.version=10.0.5.0.v202602021017
webcommons.available=true
jetty.portnum=8888
jetty.httpsportnum=8443
rentokilUi_appid=rentokilUi
rentokilUi_locales=ar,en,en_US,es
rentokilUi_sessionmgr=1
rentokilUi_appversion=1.0.0
rentokilUi_build.option=debug
rentokilUi_jspbase=/WEB-INF/
rentokilUi_devlanguage=js
apps.list=rentokilUi
webapps.loc=C:/Users/omars/Iris/workspace/webapps
plugin.loc=C:/Users/omars/Iris/workspace/bundles/com.pat.tool.keditor
rentokilUi_resfolder=C:/Users/omars/Iris/workspace/rentokilUi/resources